name: CI

on:
  push:
    tags: ['v*']
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Clone submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y lcov gcovr
        
    - name: Configure with coverage flags
      run: |
        cmake -H. -B_build \
          -DBUILD_TESTS=ON \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage" \
          -DCMAKE_C_FLAGS="--coverage -fprofile-arcs -ftest-coverage"
      
    - name: Build
      run: cmake --build _build
      
    - name: Run tests
      run: cd _build && ./RunTest
      
    - name: Generate coverage report
      working-directory: _build
      run: |
        lcov --capture \
             --directory . \
             --output-file coverage.info \
             --ignore-errors mismatch,unused,empty \
             --rc branch_coverage=1 \
             --rc geninfo_unexecuted_blocks=1
        
        lcov --remove coverage.info \
             '/usr/*' \
             '*/googletest/*' \
             '*/test/*' \
             '*/gtest/*' \
             '*/gmock/*' \
             --output-file filtered.info \
             --ignore-errors unused
             
        genhtml --branch-coverage \
                --title "Test Coverage" \
                --output-directory coverage \
                filtered.info \
                --ignore-errors unmapped,unused
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: _build/coverage

  package:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Clone submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake rpm
        
    - name: Configure
      run: cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build _build
      
    - name: Create packages
      shell: bash
      run: |
        cd _build
        if [ "$RUNNER_OS" == "Linux" ]; then
          cpack -G DEB
          cpack -G RPM
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cpack -G DragNDrop
        elif [ "$RUNNER_OS" == "Windows" ]; then
          cpack -G WIX
        fi
        
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ runner.os }}
        path: _build/*.deb,_build/*.rpm,_build/*.dmg,_build/*.msi
        
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          _build/*.deb
          _build/*.rpm
          _build/*.dmg
          _build/*.msi
