name: Build and Package
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Create minimal LICENSE file
      run: |
        if [ ! -f "LICENSE" ]; then
          echo "MIT License" > LICENSE
          echo "Copyright (c) $(date +%Y) abchihba868 " >> LICENSE
        fi
        
    - name: Prepare Windows license
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        if (!(Test-Path "LICENSE.rtf")) {
          "{\rtf1\ansi Minimal License}" | Out-File -Encoding ASCII "LICENSE.rtf"
        }

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake dpkg-dev rpm
        
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install wixtoolset -y
        
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: brew install cmake
        
    - name: Configure and Build
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Create Packages
      shell: bash
      run: |
        cd build
        if [ "$RUNNER_OS" == "Linux" ]; then
          cpack -G TGZ
          cpack -G DEB
          cpack -G RPM
        elif [ "$RUNNER_OS" == "Windows" ]; then
          cpack -G WIX -C Release
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cpack -G DragNDrop
        fi
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Packages-${{ matrix.os }}
        path: build/*
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*
