name: Build and Package
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential dpkg-dev rpm
        
    - name: Install CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install wixtoolset -y
        
    - name: Install CMake (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake
        
    - name: Verify CMake version
      run: cmake --version
        
    - name: Configure and Build
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        

    - name: Create Packages (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        cpack -G TGZ
        cpack -G DEB
        cpack -G RPM
        
    - name: Create Packages (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        cpack -G WIX -C Release -V --debug
        
    - name: Create Packages (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd build
        cpack -G DragNDrop
        
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Packages
        path: build/*.msi

    - name: Upload Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Linux-Packages
        path: |
          build/*.deb
          build/*.rpm
          build/*.tar.gz

    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Packages
        path: build/*.dmg
